name: deploy
on: [push, pull_request]

jobs:
  workflow_dispatch: 
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: JDK setup
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Start Docker Images
        run: echo $VM_PASSWORD | sudo -S ../DigiBack_java_backend/./start_docker.sh
