name: deploy
on: [push, pull_request]

jobs:
  workflow_dispatch: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: JDK setup
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      #- name: Start Docker Images
      #  run: cd ../DigiBack_java_backend/ & git pull & ./start_docker.sh
      - name: Start Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOSTNAME }}        
          username: ${{ secrets.VM_USER_USERNAME }}      
          key: ${{ secrets.VM_USER_SSH_PRIVATE_KEY }}
          port: 22    
          script: |
            set -o errexit
            # Treat unset variables as an error when substituting
            set -o nounset
            # Add required packages
            apk add --no-cache openconnect openssh-client
            # Connect to the VPN
            echo "$VPN_USER_PASSWORD" | openconnect --user=$VPN_USER_USERNAME --passwd-on-stdin --background $VPN_HOSTNAME
            # Hacky: wait for the VPN to be up
            sleep 5
            # Configure SSH
            mkdir -p ~/.ssh
            chmod 700 ~/.ssh
            # Create the SSH private key
            echo "$VM_USER_SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
            chmod 700 ~/.ssh/id_ed25519
            # Add the VM hostname to known hosts
            ssh-keyscan "$VM_HOSTNAME" > ~/.ssh/known_hosts
            chmod 644 ~/.ssh/known_hosts
            cd DigiBack_java_backend
            git pull
            ./start_docker.sh
