name: deploy new version
on: [push, pull_request]

jobs:
  workflow_dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: JDK setup
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      #- name: Start Docker Images
      #  run: cd ../DigiBack_java_backend/ & git pull & ./start_docker.sh

      - name: Install Open VPN
        run: |
          sudo apt-get install openvpn
          echo "${{ secrets.VPN_FILE }}" > .github/vpn/config.ovpn

      - name: Connect VPN
        uses: golfzaptw/action-connect-ovpn@master
        id: connect_vpn
        with:
          PING_URL: ${{ secrets.VPN_HOSTNAME }}
          FILE_OVPN: '.github/vpn/config.ovpn'
          SECRET: ${{ secrets.SECRET_USERNAME_PASSWORD }}
        env:
          CA_CRT: ${{ secrets.CA_CRT}}
          USER_CRT: ${{ secrets.VPN_USER_USERNAME }}
          USER_KEY: ${{ secrets.VPN_USER_PASSWORD }}

      - name: Check Connect VPN
        run: echo ${{ steps.connect_vpn.outputs.STATUS }}

      - name: Start Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOSTNAME }}
          username: ${{ secrets.VM_USER_USERNAME }}
          key: ${{ secrets.VM_USER_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd DigiBack_java_backend
            git pull
            ./start_docker.sh
