name: deploy
on: [push, pull_request]

jobs:
  workflow_dispatch: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: JDK setup
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build application
        run: mvn clean package install
      - name: Upload application
        uses: appleboy/scp-action@master
        with:       
          host: ${{ secrets.VM_HOSTNAME }}        
          username: ${{ secrets.VM_USER_USERNAME }}      
          key: ${{ secrets.VM_USER_SSH_PRIVATE_KEY }}
          port: 22
          source: "my-app.jar"      
          target: "~/source"
