name: deploy
on: [push, pull_request]

jobs:
  workflow_dispatch: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: JDK setup
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      #- name: Start Docker Images
      #  run: cd ../DigiBack_java_backend/ & git pull & ./start_docker.sh
      - name: Start Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOSTNAME }}        
          username: ${{ secrets.VM_USER_USERNAME }}      
          key: ${{ secrets.VM_USER_SSH_PRIVATE_KEY }}
          port: 22    
          script: |
            cd DigiBack_java_backend
            chmod -x update_docker.sh
            chmod -x start_docker.sh
            ./start_docker.sh
