name: deploy
on: [push, pull_request]

jobs:
  workflow_dispatch: 
    runs-on: ubuntu-latest
    steps:
      - name: JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build application
        run: |
          # Could also be a maven task
          mvn clean package install
      - name: Upload application
        uses: appleboy/scp-action@master
        with:       
          host: ${{ secrets.VM_HOSTNAME }}        
          username: ${{ secrets.VM_USER_USERNAME }}      
          key: ${{ secrets.VM_USER_SSH_PRIVATE_KEY }}
          port: 22
          source: "my-app.jar"      
          target: "~/source"
